Mdht release 2.0 merge
MAYHEM-Lab/cspot pull request #45
Opened 2021-07-24 18:34 UTC by shereenElSayed

I created cmake files for apps/raft , apps/dht, apps/monitor, and any subdirectories.
I updated some c files by removing the #include woofc-host, any caching calls,..
There are some problems:
--important packages need to be installed for raft and dht (shell scripts in these folders are available to install them)
--monitor cmake folder has a problem (the file causing it is commented for now)
--I am having a problem building the apps/dht/app/multi-regression with finding boost, but this might be a problem with my machine and not a general problem

2021-08-05 00:45 UTC, shereenElSayed commented
@FatihBAKIR I am having some issues with the libraries (boost, mlpack). I specified the path for boost in the code to make it work. I am sure there is a more neat way to do this. for mlpack although it is installed, I am still getting error for undefined funcion mlpack::regression::linear_regression...

2021-10-11 18:00 UTC, FatihBAKIR commented on makefile
> +CC=gcc
We don't do makefiles anymore :)

2021-10-11 18:00 UTC, FatihBAKIR commented on include/woofc.h
> +char* WoofGetFileName(WOOF* wf);
This should return a `const char*`

2021-10-11 18:00 UTC, FatihBAKIR commented on include/woofc.h
> +unsigned long WooFGetElSize(WOOF* wf, const char* wf_name);
Why do we need both the woof pointer and its name?

2021-10-11 18:02 UTC, FatihBAKIR commented on src/woofc.cpp
> +                strncat(local_name, "/", 2);
Could you explain what this is fixing?

2021-10-12 19:41 UTC, shereenElSayed commented on apps/monitor/CMakeLists.txt
> +target_include_directories(monitor PUBLIC "${CMAKE_SOURCE_DIR}/apps/monitor/include")
Yup changing that

2021-10-16 01:59 UTC, FatihBAKIR requested changes
There are only a few changes needed, looking good

2021-10-16 01:59 UTC, FatihBAKIR commented on apps/dht/CMakeLists.txt
> +pkg_search_module(OPENSSL REQUIRED openssl)
Why do we have some hard-coded paths?

2021-10-16 01:59 UTC, FatihBAKIR commented on apps/dht/apps/multi_regression/CMakeLists.txt
> +FIND_PACKAGE(Boost REQUIRED)
Use lower-case for consistency (ie. `find_package(Boost REQUIRED)`)

2021-10-16 01:59 UTC, FatihBAKIR commented on src/net/zmq/client.cpp
> +    DEBUG_LOG("%s ", str.c_str());
This will cause a lot of logs

2021-10-18 21:23 UTC, shereenElSayed commented on makefile
> +CC=gcc
I will delete this file. I was keeping the makefiles just in case of any failures and we need to take a look on them.

2021-10-18 21:23 UTC, shereenElSayed commented on makefile
> +CC=gcc
Shall I delete all makefiles in /apps?

2021-10-18 21:27 UTC, shereenElSayed commented on include/woofc.h
> +unsigned long WooFGetElSize(WOOF* wf, const char* wf_name);
Because in case of remote, we use `WooFMsgGetElSize(wf_name)` otherwise if shared, we return `wf->shared->element_size`

2021-11-03 17:35 UTC, merged